### ISSUE TITLE
Bug: meet Error when running "uer/gpt2-chinese-cluecorpussmall" from hugging face

### ISSUE THREAD

**Issue by neal2018** [dbiir/UER-py#120]
Code
```python
from transformers import AutoTokenizer, AutoModelForCausalLM, TextGenerationPipeline
tokenizer = AutoTokenizer.from_pretrained("uer/gpt2-chinese-cluecorpussmall")
model = AutoModelForCausalLM.from_pretrained("uer/gpt2-chinese-cluecorpussmall")
text_generator = TextGenerationPipeline(model, tokenizer)
print(text_generator("我", min_length=100, do_sample=True))
```

Error message
```bash
$ python test.py 
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(text_generator("我", min_length=100, do_sample=True))
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\pipelines\text_generation.py", line 147, in __call__ 
    output_sequences = self.model.generate(input_ids=input_ids, **generate_kwargs)  # BS x SL
  File "C:\Users\neal\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context        
    return func(*args, **kwargs)
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\generation_utils.py", line 940, in generate
    **model_kwargs,
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\generation_utils.py", line 1390, in sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\generation_logits_process.py", line 89, in __call__  
    scores = processor(input_ids, scores)
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\generation_logits_process.py", line 117, in __call__ 
    scores[:, self.eos_token_id] = -float("inf")
IndexError: index 50256 is out of bounds for dimension 1 with size 21128
```

Seems like `pad_token_id` is set to `50256`, which is out of the total vocab size (21128).
Is my usage wrong? Or do I need to update something in the `config.json` from hugging face?

**Comment by hhou435** [comment]
If you use AutoTokenizer here, GPT2Tokenizer will be called automatically. We are using BertTokenizer in this model, so errors will occur. In the How to use section of the model introduction, we explained in detail how to use the model

**Comment by neal2018** [comment]
Thanks for you respond! However, the same error occurs when BertTokenizer is used
```python
from transformers import BertTokenizer, GPT2LMHeadModel, TextGenerationPipeline
tokenizer = BertTokenizer.from_pretrained("uer/gpt2-chinese-cluecorpussmall")
model = GPT2LMHeadModel.from_pretrained("uer/gpt2-chinese-cluecorpussmall")
text_generator = TextGenerationPipeline(model, tokenizer)
print(text_generator("我", min_length=100, do_sample=True))
```

Error
```bash
$ python test.py
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(text_generator("我", min_length=100, do_sample=True))
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\pipelines\text_generation.py", line 147, in __call__
    output_sequences = self.model.generate(input_ids=input_ids, **generate_kwargs)  # BS x SL
  File "C:\Users\neal\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\generation_utils.py", line 940, in generate
    **model_kwargs,
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\generation_utils.py", line 1390, in sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\generation_logits_process.py", line 89, in __call__
    scores = processor(input_ids, scores)
  File "C:\Users\neal\anaconda3\lib\site-packages\transformers\generation_logits_process.py", line 117, in __call__
    scores[:, self.eos_token_id] = -float("inf")
IndexError: index 50256 is out of bounds for dimension 1 with size 21128
```

**Comment by hhou435** [comment]
The above code works in our environment and the results are normal in Huggingface's Hosted inference API (text generation).
It is recommended to clear the cache or update the transformer version.

**Comment by neal2018** [comment]
Manually setting `pad_token_id` to `0` solves the problem. Thanks for your help.

**Comment by tuzeao** [comment]
I found out `tokenizer.eos_token_id` is equal to `None`, which is strange.
set `model = GPT2LMHeadModel.from_pretrained(model_path, 
                                        pad_token_id=tokenizer.convert_tokens_to_ids("[PAD]"),
                                        eos_token_id=tokenizer.convert_tokens_to_ids("[SEP]"))` solved my problem.
