### ISSUE TITLE
convert_bert_from_huggingface_to_uer.py报错

### ISSUE THREAD

**Issue by Judenpech** [dbiir/UER-py#129]
模型来自：https://huggingface.co/bert-base-multilingual-uncased
报错：
```
Traceback (most recent call last):
  File "UER-py-master/scripts/convert_bert_from_huggingface_to_uer.py", line 66, in <module>
    main()
  File "UER-py-master/scripts/convert_bert_from_huggingface_to_uer.py", line 45, in main
    output_model["embedding.layer_norm.gamma"] = input_model["bert.embeddings.LayerNorm.weight"]
KeyError: 'bert.embeddings.LayerNorm.weight'
```

**Comment by hhou435** [comment]
您好，这是由于保存模型时transformers版本造成的参数名称不一致
您可以手动修改convert_bert_from_huggingface_to_uer.py 
文件中16，17，22，23，45，46，57，58行中的
input_model["....LayerNorm.weight"]
input_model["....LayerNorm.bias"]
为
input_model["....LayerNorm.gamma"]
input_model["....LayerNorm.beta"]

**Comment by Judenpech** [comment]
> 您好，这是由于保存模型时transformers版本造成的参数名称不一致
> 您可以手动修改convert_bert_from_huggingface_to_uer.py 
> 文件中16，17，22，23，45，46，57，58行中的
> input_model["....LayerNorm.weight"]
> input_model["....LayerNorm.bias"]
> 为
> input_model["....LayerNorm.gamma"]
> input_model["....LayerNorm.beta"]

您好，修改后出现了新的错误：
```
Traceback (most recent call last):
  File "UER-py-master/scripts/convert_bert_from_huggingface_to_uer.py", line 66, in <module>
    main()
  File "UER-py-master/scripts/convert_bert_from_huggingface_to_uer.py", line 48, in main
    convert_bert_transformer_encoder_from_huggingface_to_uer(args.layers_num, output_model, input_model)
  File "UER-py-master/scripts/convert_bert_from_huggingface_to_uer.py", line 7, in convert_bert_transformer_encoder_from_huggingface_to_uer
    for i in range(layers_num):
TypeError: 'collections.OrderedDict' object cannot be interpreted as an integer
```

**Comment by hhou435** [comment]
您好，之前的参数位置有误，已经修改了相应的代码，麻烦您下载最新的版本重新测试一下

**Comment by Judenpech** [comment]
您好，使用最新版本可以成功转换模型，但在下游run_c3.py任务中加载转换好的模型出现了新的错误：
```
Traceback (most recent call last):
  File "run_c3.py", line 257, in <module>
    main()
  File "run_c3.py", line 152, in main
    load_or_initialize_parameters(args, model)
  File "/UER-py/run_classifier.py", line 83, in load_or_initialize_parameters
    model.load_state_dict(torch.load(args.pretrained_model_path), strict=False)
  File "/home/s/anaconda3/envs/uer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MultipleChoice:
        size mismatch for embedding.word_embedding.weight: copying a param with shape torch.Size([105879, 768]) from checkpoint, the shape in current model is torch.Size([21128, 768]).
```

**Comment by hhou435** [comment]
您好，这是由于模型词典不匹配导致的，您需要到对应的模型仓库中下载词典，然后使用 --vocab_path 进行加载

**Comment by Judenpech** [comment]
您好，使用对应的词典后仍然报相同的错误，似乎是参数未被正确加载。

**Comment by hhou435** [comment]
您好，可以提供一下您的的运行命令吗，以及您是否使用的是https://huggingface.co/bert-base-multilingual-uncased仓库下的vocab.txt呢？我这里测试是可以正确加载模型的

**Comment by Judenpech** [comment]
您好，我重新检查后发现似乎是Tmux会话的问题，新建会话后就能够正常运行了。非常感谢您的耐心回复！
