### ISSUE TITLE
预训练微调结束，使用inference/run_classifier_infer.py对无标签数据进行测试报错

### ISSUE THREAD

**Issue by linwhitehat** [dbiir/UER-py#160]
具体错误如下：
Traceback (most recent call last):
  File "inference/run_classifier_infer.py", line 149, in <module>
    main()
  File "inference/run_classifier_infer.py", line 131, in main
    _, logits = model(src_batch, None, seg_batch)
  File "/home/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/pre-train/run_classifier.py", line 48, in forward
    output_emb = self.encoder(emb, seg_data)
  File "/home/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/pre-train/uer/encoders/transformer_encoder.py", line 53, in forward
    batch_size, seq_length, _ = emb.size()
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by P01son6415** [comment]
请发一下使用的预训练模型以及运行的命令

**Comment by linwhitehat** [comment]
> 请发一下使用的预训练模型以及运行的命令

我使用的预训练模型是bert，分类预测的命令如下
CUDA_VISIBLE_DEVICES=1 python3 inference/run_classifier_infer.py --load_model_path models/finetuned_model.bin --vocab_path models/vocab_test.txt --test_path datasets/all_datas/test_env/nolabel_test_dataset.tsv --prediction_path datasets/all_datas/test_env/prediction.tsv --labels_num 20 --embedding word_pos_seg --encoder transformer --mask fully_visible

**Comment by linwhitehat** [comment]
> 请发一下使用的预训练模型以及运行的命令

我在两台机子上做了测试，旧机子测试正常，新机子会报错，似乎是环境问题，但是还没有找到具体的问题
