### ISSUE TITLE
类型错误TypeError

### ISSUE THREAD

**Issue by ctrl-liuxiaohu** [dbiir/UER-py#194]
Traceback (most recent call last):
  File "pretrain.py", line 125, in <module>
    main()
  File "pretrain.py", line 121, in main
    trainer.train_and_validate(args)
  File "/data/husheng/pycharm_projects/UER-py/uer/trainer.py", line 57, in train_and_validate
    worker(args.gpu_id, None, args, model)
  File "/data/husheng/pycharm_projects/UER-py/uer/trainer.py", line 466, in worker
    trainer.train(args, gpu_id, rank, train_loader, model, optimizer, scheduler)
  File "/data/husheng/pycharm_projects/UER-py/uer/trainer.py", line 94, in train
    batch = list(next(loader_iter))
  File "/data/husheng/pycharm_projects/UER-py/uer/utils/data.py", line 445, in __iter__
    yield torch.LongTensor(src), \
TypeError: an integer is required (got type NoneType)

**Comment by ctrl-liuxiaohu** [comment]
采用的中文脱敏数据，按照词序生成词表后采用 preprocess.py 按照空格分词进行的数据预处理。
然后自行以下命令进行预训练：
机器：RTX3090 10卡
export CUDA_VISIBLE_DEVICES=8
python3 pretrain.py --dataset_path risk_dataset.pt --vocab_path models/vocab_risk.txt --output_model_path models/risk_model.bin --embedding word_pos_seg --tokenizer space --encoder transformer --gpu_ranks 0 --mask fully_visible --target mlm
报错如上。
谢谢！

**Comment by P01son6415** [comment]
TypeError: an integer is required (got type NoneType)
数据预处理有问题，传入了None

**Comment by Abigial61** [comment]
我也遇到了相同的报错，请问最后是怎么解决的呢？
数据预处理有问题，传入了None,指的是preprocess未成功吗？但是已经得到了预处理结束后的dataset.pt文件了，为什么会传入None呢？

**Comment by cservan** [comment]
Dear All,
I had the same error, this came from I have a custom PAD_TOKEN (in my case it is "<pad>" instead of "[PAD]").
I solved it by setting my custom pad token in the file "models/special_tokens_map.json".
Hope this help 
Best
