### ISSUE TITLE
请教关于MLM预训练问题

### ISSUE THREAD

**Issue by 2021ckck** [dbiir/UER-py#199]
您好！请问以下几个问题，非常感谢：

（1）请问我以BERT为基础，进行MLM的预训练，同时采用静态Span masking，请问是正确的操作吗？不知道为何，我实际训练出的模型效果反倒不如原生BERT。脚本见最后。

（2）请问以上述方式训练出来的UER模型，convert转化为huggingface模型的过程中，我采用了script文件夹中提供的convert_bert_from_uer_to_huggingface.py，其中choice选择默认的BERT还是MLM呢？ 我选择了默认的BERT，但是报错：

Traceback (most recent call last):
  File "convert_bert_from_uer_to_huggingface_cloze_long.py", line 66, in <module>
    main()
  File "convert_bert_from_uer_to_huggingface_cloze_long.py", line 51, in main
    output_model["bert.pooler.dense.weight"] = input_model["target.nsp_linear_1.weight"]
KeyError: 'target.nsp_linear_1.weight'
Traceback (most recent call last):
  File "convert_bert_from_uer_to_huggingface_cloze_short.py", line 66, in <module>
    main()
  File "convert_bert_from_uer_to_huggingface_cloze_short.py", line 51, in main
    output_model["bert.pooler.dense.weight"] = input_model["target.nsp_linear_1.weight"]
KeyError: 'target.nsp_linear_1.weight'

（2）那么，请问下，采用上述训练方式（在原生BERT模型上继续预训练MLM）后，训练出的模型还属不属于和原生BERT结构相同的模型呢？还是说只剩下了MLM的权重，NSP的权重被自动删除了？如果需要训练出的模型和原生BERT结构一样，是否target 只能采用bert呢？同时语料库corpus也需要准备NSP的那种语料库？

预训练脚本如下：
python3 preprocess.py --corpus_path cpulse_corpus/corpus.txt \
                      --vocab_path models/google_zh_vocab.txt \
                      --dataset_path mlm_base_dataset.pt \
                      --processes_num 1 --span_masking --span_geo_prob 0.3 --span_max_length 5  --target mlm						  

python3 pretrain.py --dataset_path mlm_base_dataset.pt --vocab_path models/google_zh_vocab.txt \
                    --pretrained_model_path models/google_zh_model.bin \
                    --output_model_path models/output_model.bin \
                    --config_path models/bert/base_config.json \
                    --world_size 1 --gpu_ranks 0 --learning_rate 2e-5  \
					--total_steps 50000 --save_checkpoint_steps 10000    --report_steps 1000  --batch_size 8\
					--embedding word_pos_seg --encoder transformer --mask fully_visible --target mlm

**Comment by Embedding** [comment]
感谢您的提问
（1）您的操作没有问题。span masking不一定在中文上效果更好，可以试试wwm masking
（2）由于预训练使用的是mlm，因此没有nsp相关权重，在转换的时候，target需要选择mlm
（3&4）训练出来的模型，在embedding和encoder层和原生BERT一样，在下游任务上可以一样使用。target部分只有MLM权重，没有NSP权重。NSP并不是特别重要，因此target选择bert或mlm都可以。如果要复现BERT模型，需要使用 *--target bert* ，如果复现RoBERTa模型，需要使用 *--target mlm*
