### ISSUE TITLE
pretrain RoBERTa

### ISSUE THREAD

**Issue by skye95git** [dbiir/UER-py#235]
1. I want to do incremental pre-training on the existing RoBERTa. Which RoBERTa model should I use? Download directly from Hugging Face? Do I need to script it into UER format after downloading it? Is there a conversion script if necessary?

2. RoBERTa's input corpus format is one document in a row. I am dealing with code corpus and want to change a sample into 
`natural language`+`program language`. What should I do?

https://github.com/dbiir/UER-py/blob/862526f2c256ec9d644c5fb99d9b0cbee77254f5/uer/utils/data.py#L336

Can I just change this to `[CLS] + natural language + [SEP] + program language + [EOS]`?

**Comment by hhou435** [comment]
1.If you want to use the model in UER format, you can download it directly from the link https://github.com/dbiir/UER-py/wiki/Modelzoo
2.Yes, you can customize the input by modifying the Dataset

**Comment by skye95git** [comment]
> 1.If you want to use the model in UER format, you can download it directly from the link https://github.com/dbiir/UER-py/wiki/Modelzoo 2.Yes, you can customize the input by modifying the Dataset

Thanks for your reply. I've seen the models in Modelzoo before. The RoBERTa models in Modelzoo are all trained on Chinese corpus. But what I need is the RoBERTa model pre-trained on the English corpus. How do I get it?

**Comment by hhou435** [comment]
You can download the model from huggingface and convert it to UER format by the script https://github.com/dbiir/UER-py/blob/master/scripts/convert_bert_from_huggingface_to_uer.py

**Comment by skye95git** [comment]
> You can download the model from huggingface and convert it to UER format by the script https://github.com/dbiir/UER-py/blob/master/scripts/convert_bert_from_huggingface_to_uer.py

So, RoBERTa and BERT share the same script, right? No matter converting model from UER format to Huggingface format (PyTorch) or converting model from Huggingface format (PyTorch) to UER format.

**Comment by hhou435** [comment]
You can use `--target` to select BERT or RoBERTa

**Comment by skye95git** [comment]
> You can use `--target` to select BERT or RoBERTa

If I want to use RoBERTa, can I just set `--target` to MLM?

**Comment by hhou435** [comment]
Yes

**Comment by skye95git** [comment]
> Yes

How to set `--layers_num` when I convert huggingface RoBERTa to UER?
There are different choices in the examples. Do you set the number of layers of Transformer according to your own task?

**Comment by skye95git** [comment]
> You can download the model from huggingface and convert it to UER format by the script https://github.com/dbiir/UER-py/blob/master/scripts/convert_bert_from_huggingface_to_uer.py

Hi, I have downloaded the RoBERTa from huggingface: https://huggingface.co/roberta-base/tree/main.
<img width="645" alt="12162" src="https://user-images.githubusercontent.com/41561936/146328163-7b21f66b-e392-4a3f-b2b8-a812f75869d4.PNG">
 
Then I run the script https://github.com/dbiir/UER-py/blob/master/scripts/convert_bert_from_huggingface_to_uer.py:
```
python scripts/convert_bert_from_huggingface_to_uer.py --input_model_path /platform_tech/linjiayi/UER/huggingface_model/RoBERTa/pytorch_model.bin \
                                                                            --output_model_path /platform_tech/linjiayi/UER/model/RoBERTa/uer_pytorch_model.bin \
                                                                            --layers_num 12 --target mlm
```
There is an error:
<img width="970" alt="12163" src="https://user-images.githubusercontent.com/41561936/146328694-2ca5cadc-f4cf-49d7-a791-3182eb5446b8.PNG">

What should I do?

**Comment by skye95git** [comment]
Hi,  If I want use English corpus to pre-train RoBERTa from scratch, Which dictionary should I use?
I use the `vocab.json` downloaded from huggingface,  but the instance show None:
```
python preprocess.py --corpus_path /platform_tech/linjiayi/dataset/codebase.jsonl --vocab_path /platform_tech/linjiayi/UER/huggingface_model/RoBERTa/vocab.json \
                      --dataset_path /platform_tech/linjiayi/UER/dataset/dataset.pt --processes_num 8 \
                      --dynamic_masking --target mlm
```
![image](https://user-images.githubusercontent.com/41561936/146509255-460a6f16-3b2b-462d-9c80-7b47513b27ba.png)

**Comment by hhou435** [comment]
> > You can download the model from huggingface and convert it to UER format by the script https://github.com/dbiir/UER-py/blob/master/scripts/convert_bert_from_huggingface_to_uer.py
> 
> Hi, I have downloaded the RoBERTa from huggingface: https://huggingface.co/roberta-base/tree/main. <img alt="12162" width="645" src="https://user-images.githubusercontent.com/41561936/146328163-7b21f66b-e392-4a3f-b2b8-a812f75869d4.PNG">
> 
> Then I run the script https://github.com/dbiir/UER-py/blob/master/scripts/convert_bert_from_huggingface_to_uer.py:
> 
> ```
> python scripts/convert_bert_from_huggingface_to_uer.py --input_model_path /platform_tech/linjiayi/UER/huggingface_model/RoBERTa/pytorch_model.bin \
>                                                                             --output_model_path /platform_tech/linjiayi/UER/model/RoBERTa/uer_pytorch_model.bin \
>                                                                             --layers_num 12 --target mlm
> ```
> 
> There is an error: <img alt="12163" width="970" src="https://user-images.githubusercontent.com/41561936/146328694-2ca5cadc-f4cf-49d7-a791-3182eb5446b8.PNG">
> 
> What should I do?

Hello, this is because the model parameter names do not match due to the too old version of Transformers used by the model. We have modified it in the latest code.

**Comment by hhou435** [comment]
> Hi, If I want use English corpus to pre-train RoBERTa from scratch, Which dictionary should I use? I use the `vocab.json` downloaded from huggingface, but the instance show None:
> 
> ```
> python preprocess.py --corpus_path /platform_tech/linjiayi/dataset/codebase.jsonl --vocab_path /platform_tech/linjiayi/UER/huggingface_model/RoBERTa/vocab.json \
>                       --dataset_path /platform_tech/linjiayi/UER/dataset/dataset.pt --processes_num 8 \
>                       --dynamic_masking --target mlm
> ```
> 
> ![image](https://user-images.githubusercontent.com/41561936/146509255-460a6f16-3b2b-462d-9c80-7b47513b27ba.png)
> 
> Do I need to rebuild the vocab myself?

You need to use `models/google_uncased_en_vocab.txt` in the project file

**Comment by skye95git** [comment]
> Hello, this is because the model parameter names do not match due to the too old version of Transformers used by the model. We have modified it in the latest code.

@hhou435 Hi, I have tried the latest code, there is still an error:
![image](https://user-images.githubusercontent.com/41561936/146759863-43a81280-d08e-4b15-8d54-c7049b5bdb37.png)

https://github.com/dbiir/UER-py/blob/af5232aa125ce0dc8d5d9285c6410e62ad95a298/scripts/convert_bert_from_huggingface_to_uer.py#L60

**Comment by hhou435** [comment]
Hi,You can use this script https://github.com/dbiir/UER-py/blob/master/scripts/convert_xlmroberta_from_huggingface_to_uer.py

**Comment by skye95git** [comment]
> Hi,You can use this script https://github.com/dbiir/UER-py/blob/master/scripts/convert_xlmroberta_from_huggingface_to_uer.py

The script can be used to convert successfully. But the transformed model seems a little different from Roberta. When I do incremental pre-training, there is an errer:
![image](https://user-images.githubusercontent.com/41561936/146867077-f33486cf-4eed-43da-8fd4-cc922ed5552c.png)

**Comment by skye95git** [comment]
@hhou435 Hi, every time I train MLM with my own data, the log freezes after printing the following message:
```
Start slurm job at Thu 23 Dec 2021 02:41:12 PM CST
Using distributed mode for training.
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
```
It would be hours before the pre-training logs were printed:
![image](https://user-images.githubusercontent.com/41561936/147209234-b7aeaaaf-0d40-4711-91e1-d77c9472b985.png)

The GPU was definitely being utilized during this time:
![image](https://user-images.githubusercontent.com/41561936/147209359-82461b25-011c-45f1-9138-d8a284945506.png)

The pre-training data was processed in advance(dataste.pt). I wonder what the program was doing when the log stopped printing for a few hours?

**Comment by skye95git** [comment]
The loss of pre-training is shown below:
![image](https://user-images.githubusercontent.com/41561936/147209959-3d0917f3-9c32-49e2-ab5d-61832a4ec14c.png)
Can the loss state be regarded as convergence?

**Comment by hhou435** [comment]
> > Hi,You can use this script https://github.com/dbiir/UER-py/blob/master/scripts/convert_xlmroberta_from_huggingface_to_uer.py
> 
> The script can be used to convert successfully. But the transformed model seems a little different from Roberta. When I do incremental pre-training, there is an errer: ![image](https://user-images.githubusercontent.com/41561936/146867077-f33486cf-4eed-43da-8fd4-cc922ed5552c.png)

Hello, we found that the English Roberta uploaded by huggingface requires the use of bpe tokenizer. We currently support the use of bpe tokenzier. You need to specify --tokenizer bpe --vocab_path huggingface_gpt2_vocab.txt --merges_path huggingface_gpt2_merges.txt during pre-processing and pre-training.

**Comment by hhou435** [comment]
> 

We do not need a few hours to load the data, maybe your log is saved in the print buffer

> @hhou435 Hi, every time I train MLM with my own data, the log freezes after printing the following message:
> 
> ```
> Start slurm job at Thu 23 Dec 2021 02:41:12 PM CST
> Using distributed mode for training.
> [W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
> [W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
> [W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
> [W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
> [W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
> [W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
> [W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
> [W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
> ```
> 
> It would be hours before the pre-training logs were printed: ![image](https://user-images.githubusercontent.com/41561936/147209234-b7aeaaaf-0d40-4711-91e1-d77c9472b985.png)
> 
> The GPU was definitely being utilized during this time: ![image](https://user-images.githubusercontent.com/41561936/147209359-82461b25-011c-45f1-9138-d8a284945506.png)
> 
> The pre-training data was processed in advance(dataste.pt). I wonder what the program was doing when the log stopped printing for a few hours? Loading data?

We do not need a few hours to load the data, maybe your log is saved in the print buffer？

**Comment by hhou435** [comment]
> The loss of pre-training is shown below: ![image](https://user-images.githubusercontent.com/41561936/147209959-3d0917f3-9c32-49e2-ab5d-61832a4ec14c.png) Can the loss state be regarded as convergence?

Have you shuffled the training data? The loss curve looks very fluctuating

**Comment by skye95git** [comment]
> > > Hi,You can use this script https://github.com/dbiir/UER-py/blob/master/scripts/convert_xlmroberta_from_huggingface_to_uer.py
> > 
> > 
> > The script can be used to convert successfully. But the transformed model seems a little different from Roberta. When I do incremental pre-training, there is an errer: ![image](https://user-images.githubusercontent.com/41561936/146867077-f33486cf-4eed-43da-8fd4-cc922ed5552c.png)
> 
> Hello, we found that the English Roberta uploaded by huggingface requires the use of bpe tokenizer. We currently support the use of bpe tokenzier. You need to specify --tokenizer bpe --vocab_path huggingface_gpt2_vocab.txt --merges_path huggingface_gpt2_merges.txt during pre-processing and pre-training.

Do I still use this script https://github.com/dbiir/UER-py/blob/master/scripts/convert_xlmroberta_from_huggingface_to_uer.py?

**Comment by skye95git** [comment]
> > The loss of pre-training is shown below: ![image](https://user-images.githubusercontent.com/41561936/147209959-3d0917f3-9c32-49e2-ab5d-61832a4ec14c.png) Can the loss state be regarded as convergence?
> 
> Have you shuffled the training data? The loss curve looks very fluctuating

I used the Codesearchnet dataset for six programming languages and didn't mess with the data. 

Here's the latest pre-training curve, can the loss state be regarded as convergence?
![image](https://user-images.githubusercontent.com/41561936/147443088-59ebe13d-7414-45d4-9fef-794c9bc12cbe.png)

**Comment by skye95git** [comment]
Hi, I do inference for pair classification:
```
CUDA_VISIBLE_DEVICES=3 python inference/run_classifier_infer.py --load_model_path model/pretrain-RoBERTa/query-code-6/finetuned_model.bin --vocab_path models/google_zh_vocab.txt \
                                          --test_path dataset/python/finetuning/test_nolabel.tsv \
                                          --prediction_path dataset/python/finetuning/prediction.tsv \
                                          --labels_num 2 --seq_length 128 --output_logits --output_prob \
                                          --embedding word_pos_seg --encoder transformer --mask fully_visible
```
There is an error:
```
Traceback (most recent call last):  File "inference/run_classifier_infer.py", line 145, in <module>
    main()
  File "inference/run_classifier_infer.py", line 95, in main
    model = load_model(model, args.load_model_path)  File "/home/linjiayi/UER-py-old/uer/model_loader.py", line 11, in load_model    model.load_state_dict(torch.load(model_path, map_location="cpu"), strict=False)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))RuntimeError: Error(s) in loading state_dict for Classifier:
        size mismatch for embedding.word_embedding.weight: copying a param with shape torch.Size([30522, 768]) from checkpoint, the shape in current model is torch.Size([21128, 768]).
```

I didn't have this problem with fine-tuning either. I pre-train and then fine-tune to get the checkpoint. Why checkpoint and the current model don't match?

**Comment by skye95git** [comment]
> Hello, we found that the English Roberta uploaded by huggingface requires the use of bpe tokenizer. We currently support the use of bpe tokenzier. You need to specify --tokenizer bpe --vocab_path huggingface_gpt2_vocab.txt --merges_path huggingface_gpt2_merges.txt during pre-processing and pre-training.

Hi, I use the `convert_xlmroberta_from_huggingface_to_uer.py` to convert Roberta. When I do incremental pre-training with the bpe tokenizer. , there is an error:
```
RuntimeError: Error(s) in loading state_dict for Model:
	size mismatch for embedding.position_embedding.weight: copying a param with shape torch.Size([514, 768]) f
rom checkpoint, the shape in current model is torch.Size([512, 768]).
```

**Comment by hhou435** [comment]
> > Hello, we found that the English Roberta uploaded by huggingface requires the use of bpe tokenizer. We currently support the use of bpe tokenzier. You need to specify --tokenizer bpe --vocab_path huggingface_gpt2_vocab.txt --merges_path huggingface_gpt2_merges.txt during pre-processing and pre-training.
> 
> Hi, I use the `convert_xlmroberta_from_huggingface_to_uer.py` to convert Roberta. When I do incremental pre-training with the bpe tokenizer. , there is an error:
> 
> ```
> RuntimeError: Error(s) in loading state_dict for Model:
> 	size mismatch for embedding.position_embedding.weight: copying a param with shape torch.Size([514, 768]) f
> rom checkpoint, the shape in current model is torch.Size([512, 768]).
> ```

Because the structure of the roberta model uploaded by huggingface is different from that of the bert model, the weights do not match. You can use the configuration of the xlmroberta model. The structure of this model is exactly the same as the roberta model uploaded by huggingface. When using, you need to replace [the file here](https://github.com/dbiir/UER-py/blob/master/uer/utils/constants.py#L4) with models/xlmroberta_special_tokens_map.json
