### ISSUE TITLE
执行run_classifier_infer遇到问题

### ISSUE THREAD

**Issue by LiXuefeng2020ai** [dbiir/UER-py#310]
执行run_classifier_infer遇到问题
```
Traceback (most recent call last):
  File "inference/run_classifier_infer.py", line 142, in <module>
    main()
  File "inference/run_classifier_infer.py", line 101, in main
    dataset = read_dataset(args, args.test_path)
  File "inference/run_classifier_infer.py", line 46, in read_dataset
    text_a = line[columns["text_a"]]
KeyError: 'text_a'
```

**Comment by P01son6415** [comment]
在数据的第一行增加一个 text_a 的表头，可以参考示例数据集的格式
________________________________
发件人: LiXuefeng2020ai ***@***.***>
发送时间: Wednesday, May 11, 2022 2:30:33 PM
收件人: dbiir/UER-py ***@***.***>
抄送: Subscribed ***@***.***>
主题: [dbiir/UER-py] 执行run_classifier_infer遇到问题 (Issue #310)


执行run_classifier_infer遇到问题

Traceback (most recent call last):

  File "inference/run_classifier_infer.py", line 142, in <module>

    main()

  File "inference/run_classifier_infer.py", line 101, in main

    dataset = read_dataset(args, args.test_path)

  File "inference/run_classifier_infer.py", line 46, in read_dataset

    text_a = line[columns["text_a"]]

KeyError: 'text_a'



―

**Comment by Embedding** [comment]
可能是文件编码的问题。比如推理UTF-8 with BOM编码的文件会导致上面的问题。
