### ISSUE TITLE
在使用自己的MRC数据集运行run_mrc.py时候报错

### ISSUE THREAD

**Issue by WorldWarII** [dbiir/UER-py#41]
把自己的机器阅读理解数据处理成了SQuAD数据集的格式，运行run_mrc.py
读数据和训练运行正常
在evaluate的时候报了Assertion Error
```
Traceback (most recent call last):
  File "run_mrc_test.py", line 590, in <module>
    main()
  File "run_mrc_test.py", line 575, in main
    result = evaluate(args, False)
  File "run_mrc_test.py", line 474, in evaluate
    assert len(pred_list) == len(examples)
AssertionError
```
后来尝试输出了evaluate函数运行时候的几个tensor的长度
```
len(start_pred_all):1997, len(dataset):1997
len(start_logits_all):1997, len(dataset):1997
len(pred_list):1906, len(examples):1920
```
前面两个断言是满足的 
pred_list的结果和examples的长度不等
dataset和examples的长度也不等，不过我不知道是否应该相等
我还在阅读这个脚本的代码
请问应该是哪里出了问题？

**Comment by WorldWarII** [comment]
找到原因了....是因为我的数据里面部分样本的id是重复的，所以会导致有些样本的结果被合并，最后报这个错。
