### ISSUE TITLE
preprocess和pretrain的参数target的选择

### ISSUE THREAD

**Issue by lweicdsor** [dbiir/UER-py#75]
我想用训练好的bert模型做分类，换句话说，我想在得到pretrain的模型后，用classification data 去fine tune，然后预测label。那么在preprocess和pretrain时应该选哪一个target？ bert 还是 cls？ 我准备的语料是不含标签的，一段一段的纯文字。我试着选了一下cls，会报错，所以选了bert，但是不确定这样做有无问题

**Comment by zhezhaoa** [comment]
您好
一般流程是先下载预训练模型，在领域相关的无监督语料上预训练，target可以选择bert或者mlm。不同的target需要不同格式的语料。具体的您可以在quickstart和instructions中找到相关信息。最后使用下游任务脚本run_classifier.py进行微调

我们把所有的vocabulary放在models文件夹中。您看看是不是路径给错了

**Comment by lweicdsor** [comment]
谢谢！请问对于total_steps有什么建议吗？我看到BERT的说明里提到如果语料多step不足不能收敛，语料少step太多则会过拟合，让斟酌选择，但是没有查到一般多少sentence对应多少step这样的信息

**Comment by zhezhaoa** [comment]
增量预训练，语料比较小的话（几十兆），5万步左右就可以；语料较大的话，10万步以上。可以每隔1万步就存一个checkpoint，尝试不同的checkpoint的效果

**Comment by lweicdsor** [comment]
多谢！我查了路径，路径是对的，但是还是报这个错：
python pretrain.py --dataset_path dataset.pt --vocab_path models/google_uncased_en_vocab.txt \
                    --pretrained_model_path models/google_bert_base_en.bin \
                    --config_path models/google_bert_base_en.json \
                    --output_model_path trained_gossipcop_model.bin  --gpu_ranks 0 \
                    --total_steps 30000 --save_checkpoint_steps 2000 --encoder bert --target bert

Using GPU 0 for training.
Traceback (most recent call last):
  File "pretrain.py", line 118, in <module>
    main()
  File "pretrain.py", line 114, in main
    trainer.train_and_validate(args)
  File "/content/gdrive/My Drive/UER-py/uer/trainer.py", line 37, in train_and_validate
    vocab.load(args.vocab_path)
  File "/content/gdrive/My Drive/UER-py/uer/utils/vocab.py", line 20, in load
    with open(vocab_path, mode="r", encoding="utf-8") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'google_uncased_en_vocab.txt'

**Comment by lweicdsor** [comment]
我试图用colab的GPU做pretraining， 一直有 out of memory 问题，我将batch_size降为了8，请问这是否会影响收敛或者训练精度？除了batch_size还有哪些参数会影响memory，可以适度调整呢？
我尝试了一下1000 steps，这是结果，由于我的目标是做sentences classification，请问我是不是应该看loss_mlm和acc_mlm？鉴于acc_nsp很高而acc_mlm还尚且较低，我是否应该继续训练？可以用这个训练了1000步数的model去继续训练吗？还是要用原始model？acc_mlm会像acc_nsp一样升至接近1吗？
|      100/    1000 steps|  3920.18 tokens/s| loss    3.01| loss_mlm: 2.799| loss_nsp: 0.213| acc_mlm: 0.539| acc_nsp: 0.953
|      200/    1000 steps|  3844.70 tokens/s| loss    2.34| loss_mlm: 2.340| loss_nsp: 0.000| acc_mlm: 0.567| acc_nsp: 1.000
|      300/    1000 steps|  3826.02 tokens/s| loss    2.20| loss_mlm: 2.200| loss_nsp: 0.000| acc_mlm: 0.590| acc_nsp: 1.000
|      400/    1000 steps|  3824.49 tokens/s| loss    2.16| loss_mlm: 2.160| loss_nsp: 0.002| acc_mlm: 0.593| acc_nsp: 0.999
|      500/    1000 steps|  3834.08 tokens/s| loss    2.11| loss_mlm: 2.097| loss_nsp: 0.015| acc_mlm: 0.602| acc_nsp: 0.999
|      600/    1000 steps|  3823.78 tokens/s| loss    2.11| loss_mlm: 2.112| loss_nsp: 0.000| acc_mlm: 0.598| acc_nsp: 1.000
|      700/    1000 steps|  3814.49 tokens/s| loss    2.06| loss_mlm: 2.056| loss_nsp: 0.002| acc_mlm: 0.609| acc_nsp: 0.999
|      800/    1000 steps|  3828.94 tokens/s| loss    2.03| loss_mlm: 2.033| loss_nsp: 0.000| acc_mlm: 0.611| acc_nsp: 1.000
|      900/    1000 steps|  3823.42 tokens/s| loss    2.07| loss_mlm: 2.061| loss_nsp: 0.011| acc_mlm: 0.604| acc_nsp: 0.998
|     1000/    1000 steps|  3830.61 tokens/s| loss    2.06| loss_mlm: 2.055| loss_nsp: 0.000| acc_mlm: 0.608| acc_nsp: 1.000
另外还想请教，如果有一个很大的语料文件，是否可以将它拆分成许多个小文件？这样每个小语料文件可以用很少的步数pretrain到收敛，一个语料训练至收敛得到一个新model后，用余下的新小语料文件再pretraining这个新model。请问这样做和用一个大的语料文件相比是否结果会有区别？
多谢！

**Comment by zhezhaoa** [comment]
1. batch_size低的话，对模型训练会有一定的影响，不过不大。显存不够的话，可以尝试使用小模型。
2. 现在只训练了1000步，应该继续训练，acc_mlm到70甚至80以上，再去下游任务微调，可能会有更好的效果。mlm这个任务比nsp更难，一般在大语料上，acc_mlm不会超过90
3. 建议直接用一个经过shuffle的大语料进行训练，拆成多个小语料没有必要，效果可能会变差，因为模型会更偏向于学习后面训练的语料

**Comment by mynewstart** [comment]
> 1. batch_size低的话，对模型训练会有一定的影响，不过不大。显存不够的话，可以尝试使用小模型。
> 2. 现在只训练了1000步，应该继续训练，acc_mlm到70甚至80以上，再去下游任务微调，可能会有更好的效果。mlm这个任务比nsp更难，一般在大语料上，acc_mlm不会超过90
> 3. 建议直接用一个经过shuffle的大语料进行训练，拆成多个小语料没有必要，效果可能会变差，因为模型会更偏向于学习后面训练的语料

请问预训练是不是不支持wwm，如果要对robert-wwm进行预训练，直接使用现在的版本对效果有影响吗？

**Comment by zhezhaoa** [comment]
目前开源的版本不支持WWM
可以直接加载WWM预训练模型进行预训练，模型会很快收敛
quick start和instructions中给出了不同targets的使用示例（以及需要的语料格式），如果使用`--target mlm`，语料的格式是一行一个文档，和`--target bert`需要的语料格式不一样

**Comment by zhezhaoa** [comment]
> > 1. batch_size低的话，对模型训练会有一定的影响，不过不大。显存不够的话，可以尝试使用小模型。
> > 2. 现在只训练了1000步，应该继续训练，acc_mlm到70甚至80以上，再去下游任务微调，可能会有更好的效果。mlm这个任务比nsp更难，一般在大语料上，acc_mlm不会超过90
> > 3. 建议直接用一个经过shuffle的大语料进行训练，拆成多个小语料没有必要，效果可能会变差，因为模型会更偏向于学习后面训练的语料
> 
> 请问预训练是不是不支持wwm，如果要对robert-wwm进行预训练，直接使用现在的版本对效果有影响吗？如果不用nsp任务，预训练数据的格式可以是一行吗？

目前开源的版本不支持WWM
可以直接加载WWM预训练模型进行预训练，模型会很快收敛
quick start和instructions中给出了不同targets的使用示例（以及需要的语料格式），如果使用`--target mlm`，语料的格式是一行一个文档，和`--target bert`需要的语料格式不一样

**Comment by SuMeng123** [comment]
> 增量预训练，语料比较小的话（几十兆），5万步左右就可以；语料较大的话，10万步以上。可以每隔1万步就存一个checkpoint，尝试不同的checkpoint的效果

请问bert在预训练的时候比如有warm up机制，学习率会随着step变化而变化。在做增量训练的时候，当前step是不是又得从1开始，使得学习率初期不断变得很大。比如预训练total_step=500w, 和第一次预训练total_step=250w,增量训练又一次250w，这两者是不是还是有区别的，比如warmup导致的学习率的变化。

**Comment by PatternFinder** [comment]
> 我试图用colab的GPU做pretraining， 一直有 out of memory 问题，我将batch_size降为了8，请问这是否会影响收敛或者训练精度？除了batch_size还有哪些参数会影响memory，可以适度调整呢？ 我尝试了一下1000 steps，这是结果，由于我的目标是做sentences classification，请问我是不是应该看loss_mlm和acc_mlm？鉴于acc_nsp很高而acc_mlm还尚且较低，我是否应该继续训练？可以用这个训练了1000步数的model去继续训练吗？还是要用原始model？acc_mlm会像acc_nsp一样升至接近1吗？ | 100/ 1000 steps| 3920.18 tokens/s| loss 3.01| loss_mlm: 2.799| loss_nsp: 0.213| acc_mlm: 0.539| acc_nsp: 0.953 | 200/ 1000 steps| 3844.70 tokens/s| loss 2.34| loss_mlm: 2.340| loss_nsp: 0.000| acc_mlm: 0.567| acc_nsp: 1.000 | 300/ 1000 steps| 3826.02 tokens/s| loss 2.20| loss_mlm: 2.200| loss_nsp: 0.000| acc_mlm: 0.590| acc_nsp: 1.000 | 400/ 1000 steps| 3824.49 tokens/s| loss 2.16| loss_mlm: 2.160| loss_nsp: 0.002| acc_mlm: 0.593| acc_nsp: 0.999 | 500/ 1000 steps| 3834.08 tokens/s| loss 2.11| loss_mlm: 2.097| loss_nsp: 0.015| acc_mlm: 0.602| acc_nsp: 0.999 | 600/ 1000 steps| 3823.78 tokens/s| loss 2.11| loss_mlm: 2.112| loss_nsp: 0.000| acc_mlm: 0.598| acc_nsp: 1.000 | 700/ 1000 steps| 3814.49 tokens/s| loss 2.06| loss_mlm: 2.056| loss_nsp: 0.002| acc_mlm: 0.609| acc_nsp: 0.999 | 800/ 1000 steps| 3828.94 tokens/s| loss 2.03| loss_mlm: 2.033| loss_nsp: 0.000| acc_mlm: 0.611| acc_nsp: 1.000 | 900/ 1000 steps| 3823.42 tokens/s| loss 2.07| loss_mlm: 2.061| loss_nsp: 0.011| acc_mlm: 0.604| acc_nsp: 0.998 | 1000/ 1000 steps| 3830.61 tokens/s| loss 2.06| loss_mlm: 2.055| loss_nsp: 0.000| acc_mlm: 0.608| acc_nsp: 1.000 另外还想请教，如果有一个很大的语料文件，是否可以将它拆分成许多个小文件？这样每个小语料文件可以用很少的步数pretrain到收敛，一个语料训练至收敛得到一个新model后，用余下的新小语料文件再pretraining这个新model。请问这样做和用一个大的语料文件相比是否结果会有区别？ 多谢！

我也一直有Cuda out of memory的问题，请问您这边一般常规本地单GPU训练的话，现存一般是会占用多少呢？除了减少batch_size, 和用小模型之外，是否还有别的减少VRAM占用的方式？（我现在是8GB VRAM，大部分训练会Cuda out of memory :(
