### ISSUE TITLE
报错：python scripts/convert_bert_from_uer_to_google.py --layers_num 36 --input_model_path mixed_corpus_bert_xlarge_model.bin

### ISSUE THREAD

**Issue by flytoylf** [dbiir/UER-py#89]
2020-12-28 20:15:19.459666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-12-28 20:15:20.400814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-28 20:15:20.400885: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2020-12-28 20:15:20.400896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2020-12-28 20:15:20.401379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14856 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:0d.0, compute capability: 7.0)
Traceback (most recent call last):
  File "scripts/convert_bert_from_uer_to_google.py", line 102, in <module>
    main()
  File "scripts/convert_bert_from_uer_to_google.py", line 68, in main
    output_model["bert/pooler/dense/kernel"] = input_model["target.nsp_linear_1.weight"]
KeyError: 'target.nsp_linear_1.weight'
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x2b7797fc2ac8>>
Traceback (most recent call last):
  File "/data/yangxiaohan/tool/python3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable

**Comment by P01son6415** [comment]
这是因为 mixed_corpus_bert_xlarge_model 中不包含 NSP 预训练任务，请注释掉转换脚本的 68-71 行，再次运行即可。

```
    output_model["bert/pooler/dense/kernel"] = input_model["target.nsp_linear_1.weight"]
    output_model["bert/pooler/dense/bias"] = input_model["target.nsp_linear_1.bias"]
    output_model["cls/seq_relationship/output_weights"] = input_model["target.nsp_linear_2.weight"]
    output_model["cls/seq_relationship/output_bias"] = input_model["target.nsp_linear_2.bias"]
```
