### ISSUE TITLE
使用reviews_lstm_lm_model报错

### ISSUE THREAD

**Issue by wzs951015** [dbiir/UER-py#9]
抱歉哈，我又来提问了 ==。。
我想使用reviews_lstm_lm_model来进行序列标注任务，config文件选择的是rnn_config.json，但是在导入模型时报错：
Traceback (most recent call last):
  File "tagger.py", line 383, in <module>
    main()
  File "tagger.py", line 164, in main
    bert_model.load_state_dict(torch.load(args.pretrained_model_path), strict=False)
  File "/home/wangzs/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
        size mismatch for encoder.rnn.weight_ih_l1: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([2048, 1024]).

**Comment by Embedding** [comment]
Did you specify the --encoder in tagger.py? Could you provide your command？
In fact, it is not recommended to use  reviews_lstm_lm_model for sequence labeling. 
Using BERT models pre-trained on RenMinRiBao could bring you SOTA results.

**Comment by wzs951015** [comment]
python tagger.py
 --pretrained_$MODEL_PATH/reviews_lstm_lm_model.bin \
 --vocab_path $MODEL_PATH/google_vocab.txt  \
--train_path $DATA_DIR/train.tsv \
--dev_path $DATA_DIR/dev.tsv  \
--test_path $DATA_DIR/test.tsv  \
--epochs_num 10 \
 --batch_size 32  \
--encoder lstm \
--learning_rate 1e-5 \ 
--seq_length 128 \
--config_path $MODEL_PATH/rnn_config.json  \
--bidirectional  \
--output_model_path /home/wangzs/UER-py-master/fine-tuned-models \

**Comment by Embedding** [comment]
Please remove --bidirectional .
reviews_lstm_lm_model.bin is unidirectional 
Currently, the model zoo doesn't contain bidirectional pretrained models  (like ELMO).
